#!/bin/bash
#######################
#PBS -N RUN-MSC-TCGA
#PBS -l walltime=72:00:00
#PBS -l ncpus=10,mem=200Gb
#PBS -j oe
#PBS -m ae
#PBS -M <EMAIL>
#PBS -W umask=0027
#######################

module load R/4.0.2

# Set working directory
WORK_DIR="???/deconvolution_benchmarking/04_tcga_bulk_validation"
cd $WORK_DIR

# Specify paths to data files
SC_REF="${WORK_DIR}/data/deconv/music/scRNA_ref.csv"
SC_PHENOTYPES="${WORK_DIR}/data/deconv/music/pheno.csv"
GENE_COUNTS_FILE="${WORK_DIR}/data/deconv/test/tcga_tpm_counts.csv"

# Specify paths to output
OUT_DIR="${WORK_DIR}/data/deconv/music/results/${PUR_LVL}"
mkdir -p $OUT_DIR

# Decide whether we want to use cell subtypes. If TRUE, there must be a path
USE_CELL_SUBTYPES="FALSE"
CELL_SUBTYPES_PATH="None"

# Decide whether we want to use marker genes. If TRUE, there must be a path
# USE_CELL_SUBTYPES is TRUE. USE_MARKER_GENES must be TRUE
USE_MARKER_GENES="FALSE"
MARKER_GENES_PATH="None"

# Specify path to execution scripts
SRC_DIR="???/deconvolution_benchmarking/src"
SCRIPT_PATH="${SRC_DIR}/1_run_music.R"

Rscript ${SCRIPT_PATH} \
${SC_REF} \
${SC_PHENOTYPES} \
${GENE_COUNTS_FILE} \
${USE_MARKER_GENES} \
${MARKER_GENES_PATH} \
${USE_CELL_SUBTYPES} \
${CELL_SUBTYPES_PATH} \
${OUT_DIR}
