#!/bin/bash
#######################
#PBS -N RUN-DWLS-TCGA-1
#PBS -l walltime=72:00:00
#PBS -l ncpus=10,mem=150Gb
#PBS -j oe
#PBS -m ae
#PBS -M <EMAIL>
#PBS -W umask=0027
#PBS -J 1-9
#######################

module load R/3.5.0

# Set purity level
CELL_TYPES=(
        T_cells
        Myeloid
        B_cells
        CAFs
        Normal_Epithelial
        Endothelial
        PVL
        Plasmablasts
        Cancer_Epithelial
)
CELL_TYPE="${CELL_TYPES[$PBS_ARRAY_INDEX-1]}"
echo "Running DE analysis for ${CELL_TYPE}"

# Set working directory
WORK_DIR="???/deconvolution_benchmarking/04_tcga_bulk_validation"
cd $WORK_DIR

# Specify paths to data files
SC_REF="${WORK_DIR}/data/deconv/dwls/scRNA_ref.csv"
SC_LABELS="${WORK_DIR}/data/deconv/dwls/single_cell_labels.csv"

# Specify path to execution scripts
SRC_DIR="???/deconvolution_benchmarking/src"
SCRIPT_PATH="${SRC_DIR}/1_run_dwls_1.R"

# Decide whether we want to use Seurat or MAST to build internal signature matrix
# Must be either "seurat" or "mast"
SIG_MATRIX_BUILD_METHOD="seurat"

# Specify paths to output
OUT_DIR="${WORK_DIR}/data/deconv/dwls/results_${SIG_MATRIX_BUILD_METHOD}/"
mkdir -p $OUT_DIR

# Run DWLS
Rscript ${SCRIPT_PATH} \
${SC_REF} \
${SC_LABELS} \
${CELL_TYPE} \
${OUT_DIR} \
${SIG_MATRIX_BUILD_METHOD} 
