#!/bin/bash
#######################
#PBS -N RUN-BSQ-BASSEZ-ET-AL
#PBS -l walltime=72:00:00
#PBS -l ncpus=4,mem=120Gb
#PBS -j oe
#PBS -m ae
#PBS -M <EMAIL>
#PBS -W umask=0027
#PBS -J 1-19
#######################

module load R/4.0.2

# Get tumour purity level
PURITY_LEVELS=(
        0.05
        0.1
        0.15
        0.2
        0.25
        0.3
        0.35
        0.4
        0.45
        0.5
        0.55
        0.6
        0.65
        0.7
        0.75
        0.8
        0.85
        0.9
        0.95
)
PUR_LVL="${PURITY_LEVELS[$PBS_ARRAY_INDEX-1]}"

# Set workin g directory
WORK_DIR="???/deconvolution_benchmarking/05_external_scrna_validation/bassez_et_al"
cd $WORK_DIR

# Specify paths to data files 
SC_REF="${WORK_DIR}/data/bisque/scaled_scRNA_ref.tsv"
SC_PHENOTYPES="${WORK_DIR}/data/bisque/phenotypes.tsv"
GENE_COUNTS_FILE="${WORK_DIR}/data/test/test_counts_${PUR_LVL}_pur_lvl.tsv"

# Specify paths to output
OUT_DIR="${WORK_DIR}/data/bisque/results_scaled/${PUR_LVL}"
mkdir -p $OUT_DIR

# Specify path to execution scripts
SRC_DIR="???/deconvolution_benchmarking/src"
SCRIPT_PATH="${SRC_DIR}/1_run_bisque.R"

# Decide whether we want to use marker genes. If TRUE, there must be a path
USE_MARKER_GENES="FALSE"
MARKER_GENES_PATH="None"

# Run bisque
Rscript ${SCRIPT_PATH} \
${SC_REF} \
${SC_PHENOTYPES} \
${GENE_COUNTS_FILE} \
${USE_MARKER_GENES} \
${MARKER_GENES_PATH} \
${OUT_DIR}
